# selene.toml
std = "roblox"
roblox-std-source = "pinned"

exclude = [
    "**/luau_packages/**",
    "**/lune_packages/**", 
    "**/roblox_packages/**",
    "**/roblox_server_packages/**",
    "**/.pesde/**",
    "**/out/**",
    "**/Internal/Signals.luau",
    "**/globalTypes.d.luau"
]

[config]
globals = [
    "script",
    "game", 
    "workspace",
    "_G",
]

[lints]
high_cyclomatic_complexity = "deny"

unused_variable = "warn"
mixed_table = "warn"
duplicate_keys = "warn"

undefined_variable = "allow"
incorrect_standard_library_use = "allow"
parenthese_conditions = "allow"
multiple_statements = "allow"